/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      backgroundImage: {
        'green-bg': "url('../assets/images/myea/green-bg1.png')",
      },
      colors: {
        'main-colour': '#4AAD37',
        'main-bg-colour': '#FFFFFF',
        'main-bg-dark-colour': '#000000',
        'nav-colour': '#4AAD37',
        'footer-colour': '#1F2937',
        'colour-pale': '#99DF8A',
        'colour-light': '#6DC85A',
        'colour-med': '#32931D',
        'colour-dark': '#1A7408',
        'transparent-black': 'rgba(0, 0, 0, 0.65)',
        'transparent-white': 'rgba(255, 255, 255, 0.65)',
        'main-black-text': '#000000',
        'main-white-text': '#FFFFFF',
        'dark-text': '#FFFFFF',
        'alt-text': '#000000',
        'dark-alt-text': '#FFFFFF',
        'hover-text': '#94A3B8',
        'dark-hover-text': '#94A3B8',
        'active-text': '#6B7280',
        'dark-active-text': '#6B7280',
        'placeholder-text': 'rgb(55 65 81)',
        'dark-placeholder-text': 'rgb(55 65 81)',
        'main-border': '#DDD5DB',
        'dark-border': '#FFFFFF',
        'error': '#',
        'success': '#',
        'hyperlink': '#2563EB',
        'dark-selected': '#2563EB',
      },
      fontFamily: {
        poppins: ['Poppins', 'sans-serif'],
        ecoapp: ['KGRedHands', 'sans-serif'],
      },
      gridTemplateRows: {
        reg: 'auto 1fr',
        rev: '1fr auto',
        even: '1fr 1fr 1fr',
        one: '1fr',
        special: 'auto 1fr 0.5fr',
        'a1a': 'auto 1fr auto',
        item: '50px 1fr',
      },
      gridTemplateColumns: {
        reg: 'auto 1fr',
        rev: '1fr auto',
        even: '1fr 1fr 1fr',
        one: '1fr',
        a1a: 'auto 1fr auto',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
